name: Generate SBOM

on:
  push:
    branches:
      main 

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm install
      - name: Generate CycloneDX SBOM
        run: npm run sbom:generate # Adjust this command based on your

project setup:
      - name: Upload SBOM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: ./path/to/your/sbom.xml # Adjust the path and file name